# -*- coding: utf-8 -*-
"""interpolacion_lineal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YOXTtBQ-cfePJeBLvsg3wD17siTRwASI
"""

import numpy as np

# Datos
x = [3, 5]
y = [19, 99]

# Punto a interpolar
x_interp = 4

# Interpolación lineal
f_interp = y[0] + ((y[1] - y[0]) / (x[1] - x[0])) * (x_interp - x[0])

print(f"Interpolación lineal en x = {x_interp}: {f_interp}")