# -*- coding: utf-8 -*-
"""regresion_lineal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18rwpuOOlqhcXawyGW0ikT42KPC1Ea2E9
"""

import numpy as np
import matplotlib.pyplot as plt

# Datos
x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([5.04, 8.12, 10.64, 13.18, 16.20, 20.04])

# Cálculo de coeficientes a1 y a0
n = len(x)
sum_x = np.sum(x)
sum_y = np.sum(y)
sum_xy = np.sum(x * y)
sum_x2 = np.sum(x**2)

a1 = (n * sum_xy - sum_x * sum_y) / (n * sum_x2 - sum_x**2)
a0 = (sum_y - a1 * sum_x) / n

print(f"Función de regresión lineal: f(x) = {a0:.3f} + {a1:.3f}x")

# Gráfica
plt.scatter(x, y, color='red', label='Datos')
plt.plot(x, a0 + a1 * x, label='Regresión lineal', color='blue')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.title('Regresión Lineal por Mínimos Cuadrados')
plt.legend()
plt.grid()
plt.show()